FROM php:8.2-fpm

# Install only essential dependencies
RUN apt-get update && apt-get install -y \
    zip unzip \
    && rm -rf /var/lib/apt/lists/*

# Install minimal PHP extensions
RUN docker-php-ext-install pdo_mysql

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www/html

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]